### PR TITLE
Add container and more details to sc3

### PR DESCRIPTION
**Pull request by pcm32**
As per request by Jean Chang, this helps complete the sc3 entry.

### CODE REVIEW

**Comment by jlchang** [comment]
Hi Pablo,

Thanks for supplying a docker URL for SC3. The SC3 submission is currently lacking two components:
1. A way for an end user (in this case a portal developer) to validate that their new instantiation of SC3 generates expected results for a given test case.
2. A docker container that supports the ability to perform the above validation

To this end, I've been working with Martin Hemberg on the following sc3 submission details:
https://github.com/HumanCellAtlas/data-portal-content/blob/jlchang-method-details/content/analyze/methods/sc3.md

The docker container for this "in-progress" submission would have the "run_sc3.R" script which supports a --validate option that compares output generated from the last deterministic step of sc3 (sc3_calc_transfs) with precomputed output provided by Martin's team. (There are several small logistical issues that have delayed a registered docker image for this submission)

Does the docker container at https://quay.io/repository/biocontainers/bioconductor-sc3 support similar validation functionality?

Also, we would want to include documentation on how to use the R wrapper scripts provided in the sc3 container (presumably similar to the README at https://github.com/ebi-gene-expression-group/scanpy-scripts).

As for the docker image info, is this acceptable for the SC3 submission (we want to reference tagged images and not "latest"):
docker pull quay.io/biocontainers/bioconductor-sc3:1.10.0--r351hf484d3e_0

As I mentioned to Jon, we would want to recognize the work that your group has done so the submission should have two sets of information, one set for the methodologist and one set for your group as the maintainer of the docker image and the wrapper scripts that make it possible to programmatically access the method. See "Packages submitted in collaboration with a methodologist" at https://prod.data.humancellatlas.org/contribute/analysis-tools-registry.

Please let me know about:
validation in the proposed new docker image at quay.io
confirm the correct docker image tag is being referenced
provide the correct information for the "maintainer" role for SC3

**Comment by pcm32** [comment]
> validation in the proposed new docker image at quay.io
I'm not aware if current tag at biocontainers would support the --validate tag

> confirm the correct docker image tag is being referenced
Yes, the tag that you mentioned seems to be the latest version available. I did it the way I did on the PR because I copied the structure from your STREAM entry I think (as I realised the link I added is not what you would use directly to do a pull). But I can change it to a "pullable" URI instead.

> provide the correct information for the "maintainer" role for SC3
Well, we are not really maintainers of anything regarding the sc3 package itself, so I'm not sure we should go there. I was under the impression that the best thing to do was to add another sc3-scripts entry to your repo, where we would point to its container, maintainers (us in this case), etc. Should we go for that?

By the way, it might simplify things if your team would have some script to just extract things from the bioconda tool manifest to fill in most of the skeleton for the markdown used here. Have you considered that? It would make things faster.

**Comment by jlchang** [comment]
> I'm not aware if current tag at biocontainers would support the --validate option.
The --validate option comes from a script that I've written to support the sc3 submission. The script could run as-is in the biocontainers bioconductor-sc3 image with the installation of three additional R packages but the script and the reference output file should either be in a code repository or (at minimum) in the docker image.

> I copied the structure from your STREAM entry 
Behind the scenes we've restructured what the new "detail page" for Registry entries will look like, the current STREAM entry can be seen in this branch: https://github.com/HumanCellAtlas/data-portal-content/blob/jlchang-method-details/content/analyze/methods/stream.md

> Well, we are not really maintainers of anything regarding the sc3 package

Agreed and "maintainers" is not the right word to use but both sets of code enable one method so it will be less confusing for developers coming to the Registry to find one entry for the method. Can you suggest a word (or phrase) that would more appropriately describe the relationship of your team to the method?

> By the way, it might simplify things if your team would have some script to just extract things from the bioconda tool manifest 

The scale of the Registry is currently modest so automation has been deferred until a later time.

**Comment by jlchang** [comment]
Ultimately, it was mutually agreed that the bioconductor-sc3-scripts container would be used instead of bioconductor-sc3. Closing this ticket as the update work proceeded down and different path.

**Pull request closed without merging**
