### PR TITLE
Update quick-start-guide.md

### PR DESCRIPTION
**Pull request by jodihir**
made a few edits, and I have some questions

### CODE REVIEW

**Comment by jodihir** [comment]
@kozbo The section called "Processing the Data" - is it really about processing, or more about how to use the data in analyses? I just want to make the distinction between that heading and "Data Processing Pipelines"... Also, in the section on downloading the manifest, after it's downloaded you say to print the help using this command: hca dss download_manifest --help'
I think this is a jump from the browser to the CLI, but can you state that if it is?  (A user like me doesn't necessarily know what window to type that in.) And printing the help is optional, right, in terms of moving forward to download the files?

**Comment by NoopDog** [comment]
@kozbo is this ok to merge? Thx

**Comment by kozbo** [comment]
I think that we can merge this now. We can split out the specific CLI installation instructions later. This should be good for CBeta

**Comment by NoopDog** [comment]
@kozbo @jodihir this is merged. Thx

**Pull request closed without merging**
