### PR TITLE
Fix "Join HCA Slack" URL

### PR DESCRIPTION
**Pull request by kislyuk**

### CODE REVIEW

**Comment by NoopDog** [comment]
Thanks @kislyuk  will let you know when this is deployed.

**Comment by NoopDog** [comment]
Hi @kislyuk 

How is this looking?
https://dev.data.humancellatlas.org/contact/join-the-discussion 

IF this looks OK i can deploy on through to prod.

Cheers,
Dave

**Comment by kislyuk** [comment]
Thanks @NoopDog. Looks great! Also, we should add `#dcp-ops-help` for questions for the DCP Operations team, but that's a separate issue.

**Comment by NoopDog** [comment]
Ok this is deployed to prod

https://prod.data.humancellatlas.org/contact/join-the-discussion

Thanks for fixing @kislyuk

**Pull request merged**
