### PR TITLE
Updated contributing data landing page

### PR DESCRIPTION
**Pull request by malloryfreeberg**
This PR includes updates to all the content in the contributing/overview/overview page.

This PR requires the following updates to the page layout:
- [ ] Removal of the /contribute/overview/what-to-prepare link in the left-hand navigation
- [ ] Probably removal of the whole left-hand navigation since there will now only be 1 element in it
- [ ] Moving of the `contact-us.md`, `prepare-metadata.md`, `upload-data.md`, and `see-and-share.md` icons to the spot indicated
- [ ] Removal of the "The Atlas is built by the Community" title and the image directly below it

I will make a separate PR in the data-portal repo for the above points.

### CODE REVIEW

**Comment by lauraclarke** [comment]
What is the timeline on this review, I won't be able to get to it before November 6th?

**Comment by malloryfreeberg** [comment]
@lauraclarke I think Oct 28 was when we wanted everything to be reviewed (according to the repo milestone). Can someone else review? Norman?

**Comment by malloryfreeberg** [comment]
@claymfischer Would you be able to have a look at this data portal content and provide feedback before October 28? Laura and Norman are in grant writing mode, but we need someone else to go over the text and review for clarity and usefulness from a data contributor perspective.

**Comment by claymfischer** [comment]
Sure thing @malloryfreeberg! I'll take a look shortly.

**Comment by NoopDog** [comment]
@malloryfreeberg @claymfischer this content is merged. Please make any updates either directly to master or in a new PR. Thanks.

**Comment by matthewspeir** [comment]
'Supported Data Types' section: RNA seq --> RNA-seq (Wikipedia article looks to use hyphenated version for entire article: https://en.wikipedia.org/wiki/RNA-Seq)

Also in the 'Supported Data Types' section, I don't think this sentence is true as we can't currently process **ALL** SS2/10x v2 data (unless I'm misunderstanding the issues with processing the rsatija 10X dataset):
>All submitted SmartSeq2 and 10X v2 experiments will be processed by our data processing pipelines 

Lastly, the 'Supported Data Types' section seems pretty heavy on the discussion of current analysis pipelines. Is none of this mentioned elsewhere in the Data Portal? If so, I'd recommend cutting the large paragraphs under each of the bullet points and just include a sentence at the end of this section that points users to a detailed discussion of current pipeline progress elsewhere.

---

This portion of a sentence in the 'Your data in the HCA' section is a bit awkward:
> In order to be able to process your data at cellular resolution

I think it should be worded as:
> In order to be able to process your cellular resolution data

Under 'Analysis Output': single cell --> single-cell (this seems to be the standard for many journal articles); RNAseq --> RNA-seq

Is the 'also' necessary in this sentence under the 'Analysis Output' section?
> For SmartSeq2 and 10X v2 single cell RNAseq experiments, the data will also be processed by our standard analysis pipelines.

Also under 'Analysis Output' section, in this sentence:
>Your data will also be available for use directly in analysis applications available through the Data Portal.

The words 'analysis applications' links to the dev version of the Data Portal of the site. Is there no way to make this link relative to the site it's on? e.g. if you're on dev it goes to the dev Data Portal, but if you're looking at the page on staging/etc. it goes to staging/etc. This is also true of the 'Data Browser' link in the intro paragraph of the 'Your data in the HCA' section. 

---

Under 'Repository accessions', in the second sentence of the last paragraph: 'practice' --> 'practices'

**Comment by jodihir** [comment]
Hi, in the data processing pipeline docs we are hyphenating Smart-seq2 to be consistent with the original paper about this technique by Picelli, et al: Smart-seq2 for sensitive full-length transcriptome profiling in single cells (https://www.nature.com/articles/nmeth.2639).

To be consistent would you be OK with doing that as well?

**Comment by gabsie** [comment]
@matthewspeir  - I wanted to make it clear which of the data types will also be processed by HCA - because this is supposed to be part of the value proposition.

There might be better ways to phrase that, though. The aim is to inform submitters whether their type of data will be processed or not.

**Comment by claymfischer** [comment]
In addition to the above (Matt’s comments and hyphenating smart-Seq2 and RNA-seq), what if we move the bit about consent to first in the list? Emphasizes how important consent is.

As for managing expectations, the value statement is very important but I am not convinced we should explicitly state which assay+species will have analysis output in this section. It could be best to mention that data sets which can be run in a pipeline will have analysis output available. We can then provide a link to the secondary analysis portal content so readers can see the available pipelines. It would be confusing seeing support for 10X, but having to make explicit statements such as no support demuxlet, for instance.

**Pull request closed without merging**
